import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, ApiError } from '../lib/api'
import type { ManagerTalentDetail, TalentSubmission } from '../types'
export function ManagerTalentApprovalDetailPage() {
  const { publicId = '' } = useParams(); const client = useQueryClient(); const [reason, setReason] = useState(''); const [message, setMessage] = useState<string|null>(null)
  const query = useQuery({ queryKey: ['manager-talent-detail', publicId], queryFn: () => api<ManagerTalentDetail>(`/api/v1/manager/talent-submissions/${publicId}`) })
  const mutation = useMutation({ mutationFn: (action: 'approve'|'return') => { if (!query.data) throw new Error('申請がありません'); return api<TalentSubmission>(`/api/v1/manager/talent-submissions/${publicId}/${action}`, { method: 'POST', body: JSON.stringify(action === 'approve' ? { version: query.data.submission.version } : { version: query.data.submission.version, reason }) }) }, onSuccess: async (_, action) => { setMessage(action === 'approve' ? '承認して正式情報へ反映しました。' : '本人へ差し戻しました。'); await client.invalidateQueries({ queryKey: ['manager-talent-detail', publicId] }); await client.invalidateQueries({ queryKey: ['manager-talent'] }) }, onError: (error) => setMessage(error instanceof ApiError ? error.problem.detail : '処理できませんでした') })
  if (!query.data) return <div className="state-card">申請を読み込んでいます…</div>; const data = query.data
  return <><div className="page-heading"><div><span className="eyebrow">READ ONLY REVIEW</span><h1>{data.employee.displayName}さんの申請</h1><p>申請内容は変更せず、承認または理由付きで差し戻します</p></div><span className="status warning">{data.submission.status}</span></div><div className="decision-grid"><section className="card"><h2>申請内容</h2><pre>{JSON.stringify(data.submission.payload, null, 2)}</pre>{data.approvedPredecessorPayload && <><h2>現在の正式値</h2><pre>{JSON.stringify(data.approvedPredecessorPayload, null, 2)}</pre></>}{data.attachments.map((file) => <p key={file.publicId}><a className="text-link" href={`/api/v1/talent-attachments/${file.publicId}`}>{file.fileName}</a></p>)}</section><section className="card"><label>差戻し理由<textarea maxLength={1000} value={reason} onChange={(e) => setReason(e.target.value)} /></label>{message && <div className={mutation.isError ? 'error-banner' : 'success-banner'}>{message}</div>}<div className="form-actions"><button className="secondary-button" disabled={!reason.trim() || mutation.isPending} onClick={() => mutation.mutate('return')}>差し戻す</button><button className="primary-button" disabled={mutation.isPending} onClick={() => mutation.mutate('approve')}>承認する</button></div><Link className="text-link back-link" to="/approvals/talent">← 一覧へ戻る</Link></section></div></>
}
